import config



API_PUBLIC = config.API_KEY
API_SECRET = config.API_SECRET_KEY
ACCESS_TOKEN = config.ACCESS_TOKEN
ACCESS_TOKEN_SECRET = config.ACCESS_TOKEN_SECRET


print(API_PUBLIC)
print(API_SECRET)
print(ACCESS_TOKEN)
print(ACCESS_TOKEN_SECRET)
